version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    env_file: 'env.influxdb'
    ports:
      - "8086:8086"
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file: 'env.grafana'
    links:
      - influxdb
    volumes:
      - /srv/docker/grafana/data:/var/lib/grafana
